/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppMisPostulacionesRouteImport } from './routes/_authenticated/app.mis-postulaciones'
import { Route as AuthenticatedAppGtRouteImport } from './routes/_authenticated/app.gt'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppTurnosIndexRouteImport } from './routes/_authenticated/app.turnos.index'
import { Route as AuthenticatedAppTurnosIdRouteImport } from './routes/_authenticated/app.turnos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMisPostulacionesRoute =
  AuthenticatedAppMisPostulacionesRouteImport.update({
    id: '/mis-postulaciones',
    path: '/mis-postulaciones',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGtRoute = AuthenticatedAppGtRouteImport.update({
  id: '/gt',
  path: '/gt',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTurnosIndexRoute =
  AuthenticatedAppTurnosIndexRouteImport.update({
    id: '/turnos/',
    path: '/turnos/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTurnosIdRoute =
  AuthenticatedAppTurnosIdRouteImport.update({
    id: '/turnos/$id',
    path: '/turnos/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/gt': typeof AuthenticatedAppGtRoute
  '/app/mis-postulaciones': typeof AuthenticatedAppMisPostulacionesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/turnos/$id': typeof AuthenticatedAppTurnosIdRoute
  '/app/turnos/': typeof AuthenticatedAppTurnosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/gt': typeof AuthenticatedAppGtRoute
  '/app/mis-postulaciones': typeof AuthenticatedAppMisPostulacionesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/turnos/$id': typeof AuthenticatedAppTurnosIdRoute
  '/app/turnos': typeof AuthenticatedAppTurnosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/gt': typeof AuthenticatedAppGtRoute
  '/_authenticated/app/mis-postulaciones': typeof AuthenticatedAppMisPostulacionesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/turnos/$id': typeof AuthenticatedAppTurnosIdRoute
  '/_authenticated/app/turnos/': typeof AuthenticatedAppTurnosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/admin'
    | '/app/gt'
    | '/app/mis-postulaciones'
    | '/app/'
    | '/app/turnos/$id'
    | '/app/turnos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/admin'
    | '/app/gt'
    | '/app/mis-postulaciones'
    | '/app'
    | '/app/turnos/$id'
    | '/app/turnos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/gt'
    | '/_authenticated/app/mis-postulaciones'
    | '/_authenticated/app/'
    | '/_authenticated/app/turnos/$id'
    | '/_authenticated/app/turnos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mis-postulaciones': {
      id: '/_authenticated/app/mis-postulaciones'
      path: '/mis-postulaciones'
      fullPath: '/app/mis-postulaciones'
      preLoaderRoute: typeof AuthenticatedAppMisPostulacionesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gt': {
      id: '/_authenticated/app/gt'
      path: '/gt'
      fullPath: '/app/gt'
      preLoaderRoute: typeof AuthenticatedAppGtRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/turnos/': {
      id: '/_authenticated/app/turnos/'
      path: '/turnos'
      fullPath: '/app/turnos/'
      preLoaderRoute: typeof AuthenticatedAppTurnosIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/turnos/$id': {
      id: '/_authenticated/app/turnos/$id'
      path: '/turnos/$id'
      fullPath: '/app/turnos/$id'
      preLoaderRoute: typeof AuthenticatedAppTurnosIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppGtRoute: typeof AuthenticatedAppGtRoute
  AuthenticatedAppMisPostulacionesRoute: typeof AuthenticatedAppMisPostulacionesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppTurnosIdRoute: typeof AuthenticatedAppTurnosIdRoute
  AuthenticatedAppTurnosIndexRoute: typeof AuthenticatedAppTurnosIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppGtRoute: AuthenticatedAppGtRoute,
  AuthenticatedAppMisPostulacionesRoute: AuthenticatedAppMisPostulacionesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppTurnosIdRoute: AuthenticatedAppTurnosIdRoute,
  AuthenticatedAppTurnosIndexRoute: AuthenticatedAppTurnosIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
